POST http://119.3.170.17:80/oc/openapi/sign
content-Type:application/json

{
    "appKey":"411f945a89384b4099109cc0be5c4e54",
    "secret":"302b122cdd91449f8c5fc4c474b6c53b"
}
> {% client.global.set("token", response.body.data.access_token);%}

###获取组织信息
GET http://119.3.170.17:80/oc/service/queryOrg
Authorization: {{token}}


###获取设备列表
GET http://119.3.170.17:80/oc/service/ video.GetVideoDetailInfo?currPage=1&pageSize=100
Authorization: {{token}}

###视频播放
GET http://119.3.170.17:80/oc/service/video.GetCameraUrl?cameraNum=cc1d37df-ceea-4e45-a4c0-224484eec654&videoSource=1&videoType=1&videoRate=0
Authorization: {{token}}